namespace ComarchTools.Schemas
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("Document-OrderResponse", Namespace = "", IsNullable = false)]
    public partial class DocumentOrderResponse
    {

        private Header orderResponseHeaderField;

        private Parties orderResponsePartiesField;

        private Line[] orderResponseLinesField;

        private Summary orderResponseSummaryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderResponse-Header")]
        public Header OrderResponseHeader
        {
            get
            {
                return this.orderResponseHeaderField;
            }
            set
            {
                this.orderResponseHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderResponse-Parties")]
        public Parties OrderResponseParties
        {
            get
            {
                return this.orderResponsePartiesField;
            }
            set
            {
                this.orderResponsePartiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("OrderResponse-Lines")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Line[] OrderResponseLines
        {
            get
            {
                return this.orderResponseLinesField;
            }
            set
            {
                this.orderResponseLinesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderResponse-Summary")]
        public Summary OrderResponseSummary
        {
            get
            {
                return this.orderResponseSummaryField;
            }
            set
            {
                this.orderResponseSummaryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Header
    {

        private string orderResponseNumberField;

        private System.DateTime orderResponseDateField;

        private System.DateTime expectedDeliveryDateField;

        private bool expectedDeliveryDateFieldSpecified;

        private string expectedDeliveryTimeField;

        private string orderNumberField;

        private System.DateTime orderDateField;

        private bool orderDateFieldSpecified;

        private messageType messageTypeField;

        private bool messageTypeFieldSpecified;

        private responseType responseTypeField;

        private string incompleteRealizationReasonField;

        private string remarksField;

        private string currencyField;

        /// <remarks/>
        public string OrderResponseNumber
        {
            get
            {
                return this.orderResponseNumberField;
            }
            set
            {
                this.orderResponseNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime OrderResponseDate
        {
            get
            {
                return this.orderResponseDateField;
            }
            set
            {
                this.orderResponseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime ExpectedDeliveryDate
        {
            get
            {
                return this.expectedDeliveryDateField;
            }
            set
            {
                this.expectedDeliveryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpectedDeliveryDateSpecified
        {
            get
            {
                return this.expectedDeliveryDateFieldSpecified;
            }
            set
            {
                this.expectedDeliveryDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ExpectedDeliveryTime
        {
            get
            {
                return this.expectedDeliveryTimeField;
            }
            set
            {
                this.expectedDeliveryTimeField = value;
            }
        }

        /// <remarks/>
        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderDateSpecified
        {
            get
            {
                return this.orderDateFieldSpecified;
            }
            set
            {
                this.orderDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public messageType MessageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MessageTypeSpecified
        {
            get
            {
                return this.messageTypeFieldSpecified;
            }
            set
            {
                this.messageTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public responseType ResponseType
        {
            get
            {
                return this.responseTypeField;
            }
            set
            {
                this.responseTypeField = value;
            }
        }

        /// <remarks/>
        public string IncompleteRealizationReason
        {
            get
            {
                return this.incompleteRealizationReasonField;
            }
            set
            {
                this.incompleteRealizationReasonField = value;
            }
        }

        /// <remarks/>
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }

        /// <remarks/>
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum messageType
    {

        /// <remarks/>
        OA,

        /// <remarks/>
        OR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum responseType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("29")]
        Item29,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Summary
    {

        private string totalLinesField;

        private decimal totalOrderedAmountField;

        private bool totalOrderedAmountFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string TotalLines
        {
            get
            {
                return this.totalLinesField;
            }
            set
            {
                this.totalLinesField = value;
            }
        }

        /// <remarks/>
        public decimal TotalOrderedAmount
        {
            get
            {
                return this.totalOrderedAmountField;
            }
            set
            {
                this.totalOrderedAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalOrderedAmountSpecified
        {
            get
            {
                return this.totalOrderedAmountFieldSpecified;
            }
            set
            {
                this.totalOrderedAmountFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Item
    {

        private string lineNumberField;

        private string orderLineNumberField;

        private string eANField;

        private itemStatus lineItemStatusField;

        private string supplierItemCodeField;

        private string buyerItemCodeField;

        private string packageEANField;

        private string itemDescriptionField;

        private decimal orderedQuantityField;

        private decimal quantityToBeDeliveredField;

        private bool quantityToBeDeliveredFieldSpecified;

        private decimal orderedUnitPacksizeField;

        private bool orderedUnitPacksizeFieldSpecified;

        private decimal quantityDifferenceField;

        private bool quantityDifferenceFieldSpecified;

        private unitOfMeasure unitOfMeasureField;

        private bool unitOfMeasureFieldSpecified;

        private decimal orderedUnitNetPriceField;

        private bool orderedUnitNetPriceFieldSpecified;

        private string orderCurrencyField;

        private decimal availableStockField;

        private bool availableStockFieldSpecified;

        private decimal discountField;

        private bool discountFieldSpecified;

        private decimal taxRateField;

        private bool taxRateFieldSpecified;

        private string taxCategoryCodeField;

        private System.DateTime expectedDeliveryDateField;

        private bool expectedDeliveryDateFieldSpecified;

        private string expectedDeliveryTimeField;

        private System.DateTime expirationDateField;

        private bool expirationDateFieldSpecified;

        private string promotionReferenceField;

        private decimal packageNumberField;

        private bool packageNumberFieldSpecified;

        private packageType packageTypeField;

        private bool packageTypeFieldSpecified;

        private string remarksField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string LineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string OrderLineNumber
        {
            get
            {
                return this.orderLineNumberField;
            }
            set
            {
                this.orderLineNumberField = value;
            }
        }

        /// <remarks/>
        public string EAN
        {
            get
            {
                return this.eANField;
            }
            set
            {
                this.eANField = value;
            }
        }

        /// <remarks/>
        public itemStatus LineItemStatus
        {
            get
            {
                return this.lineItemStatusField;
            }
            set
            {
                this.lineItemStatusField = value;
            }
        }

        /// <remarks/>
        public string SupplierItemCode
        {
            get
            {
                return this.supplierItemCodeField;
            }
            set
            {
                this.supplierItemCodeField = value;
            }
        }

        /// <remarks/>
        public string BuyerItemCode
        {
            get
            {
                return this.buyerItemCodeField;
            }
            set
            {
                this.buyerItemCodeField = value;
            }
        }

        /// <remarks/>
        public string PackageEAN
        {
            get
            {
                return this.packageEANField;
            }
            set
            {
                this.packageEANField = value;
            }
        }

        /// <remarks/>
        public string ItemDescription
        {
            get
            {
                return this.itemDescriptionField;
            }
            set
            {
                this.itemDescriptionField = value;
            }
        }

        /// <remarks/>
        public decimal OrderedQuantity
        {
            get
            {
                return this.orderedQuantityField;
            }
            set
            {
                this.orderedQuantityField = value;
            }
        }

        /// <remarks/>
        public decimal QuantityToBeDelivered
        {
            get
            {
                return this.quantityToBeDeliveredField;
            }
            set
            {
                this.quantityToBeDeliveredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityToBeDeliveredSpecified
        {
            get
            {
                return this.quantityToBeDeliveredFieldSpecified;
            }
            set
            {
                this.quantityToBeDeliveredFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal OrderedUnitPacksize
        {
            get
            {
                return this.orderedUnitPacksizeField;
            }
            set
            {
                this.orderedUnitPacksizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderedUnitPacksizeSpecified
        {
            get
            {
                return this.orderedUnitPacksizeFieldSpecified;
            }
            set
            {
                this.orderedUnitPacksizeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal QuantityDifference
        {
            get
            {
                return this.quantityDifferenceField;
            }
            set
            {
                this.quantityDifferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityDifferenceSpecified
        {
            get
            {
                return this.quantityDifferenceFieldSpecified;
            }
            set
            {
                this.quantityDifferenceFieldSpecified = value;
            }
        }

        /// <remarks/>
        public unitOfMeasure UnitOfMeasure
        {
            get
            {
                return this.unitOfMeasureField;
            }
            set
            {
                this.unitOfMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitOfMeasureSpecified
        {
            get
            {
                return this.unitOfMeasureFieldSpecified;
            }
            set
            {
                this.unitOfMeasureFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal OrderedUnitNetPrice
        {
            get
            {
                return this.orderedUnitNetPriceField;
            }
            set
            {
                this.orderedUnitNetPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderedUnitNetPriceSpecified
        {
            get
            {
                return this.orderedUnitNetPriceFieldSpecified;
            }
            set
            {
                this.orderedUnitNetPriceFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string OrderCurrency
        {
            get
            {
                return this.orderCurrencyField;
            }
            set
            {
                this.orderCurrencyField = value;
            }
        }

        /// <remarks/>
        public decimal AvailableStock
        {
            get
            {
                return this.availableStockField;
            }
            set
            {
                this.availableStockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailableStockSpecified
        {
            get
            {
                return this.availableStockFieldSpecified;
            }
            set
            {
                this.availableStockFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscountSpecified
        {
            get
            {
                return this.discountFieldSpecified;
            }
            set
            {
                this.discountFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal TaxRate
        {
            get
            {
                return this.taxRateField;
            }
            set
            {
                this.taxRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxRateSpecified
        {
            get
            {
                return this.taxRateFieldSpecified;
            }
            set
            {
                this.taxRateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string TaxCategoryCode
        {
            get
            {
                return this.taxCategoryCodeField;
            }
            set
            {
                this.taxCategoryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime ExpectedDeliveryDate
        {
            get
            {
                return this.expectedDeliveryDateField;
            }
            set
            {
                this.expectedDeliveryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpectedDeliveryDateSpecified
        {
            get
            {
                return this.expectedDeliveryDateFieldSpecified;
            }
            set
            {
                this.expectedDeliveryDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ExpectedDeliveryTime
        {
            get
            {
                return this.expectedDeliveryTimeField;
            }
            set
            {
                this.expectedDeliveryTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime ExpirationDate
        {
            get
            {
                return this.expirationDateField;
            }
            set
            {
                this.expirationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationDateSpecified
        {
            get
            {
                return this.expirationDateFieldSpecified;
            }
            set
            {
                this.expirationDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string PromotionReference
        {
            get
            {
                return this.promotionReferenceField;
            }
            set
            {
                this.promotionReferenceField = value;
            }
        }

        /// <remarks/>
        public decimal PackageNumber
        {
            get
            {
                return this.packageNumberField;
            }
            set
            {
                this.packageNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackageNumberSpecified
        {
            get
            {
                return this.packageNumberFieldSpecified;
            }
            set
            {
                this.packageNumberFieldSpecified = value;
            }
        }

        /// <remarks/>
        public packageType PackageType
        {
            get
            {
                return this.packageTypeField;
            }
            set
            {
                this.packageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackageTypeSpecified
        {
            get
            {
                return this.packageTypeFieldSpecified;
            }
            set
            {
                this.packageTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum itemStatus
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum unitOfMeasure
    {

        /// <remarks/>
        KGM,

        /// <remarks/>
        PCE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum packageType
    {

        /// <remarks/>
        CT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Line
    {

        private Item lineItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line-Item")]
        public Item LineItem
        {
            get
            {
                return this.lineItemField;
            }
            set
            {
                this.lineItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Party
    {

        private string iLNField;

        private string taxIDField;

        private string codeByBuyerField;

        private string nameField;

        private string streetAndNumberField;

        private string cityNameField;

        private string postalCodeField;

        private string countryField;

        /// <remarks/>
        public string ILN
        {
            get
            {
                return this.iLNField;
            }
            set
            {
                this.iLNField = value;
            }
        }

        /// <remarks/>
        public string TaxID
        {
            get
            {
                return this.taxIDField;
            }
            set
            {
                this.taxIDField = value;
            }
        }

        /// <remarks/>
        public string CodeByBuyer
        {
            get
            {
                return this.codeByBuyerField;
            }
            set
            {
                this.codeByBuyerField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string StreetAndNumber
        {
            get
            {
                return this.streetAndNumberField;
            }
            set
            {
                this.streetAndNumberField = value;
            }
        }

        /// <remarks/>
        public string CityName
        {
            get
            {
                return this.cityNameField;
            }
            set
            {
                this.cityNameField = value;
            }
        }

        /// <remarks/>
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Parties
    {

        private Party buyerField;

        private Party invoiceeField;

        private Party sellerField;

        private Party deliveryPointField;

        private Party shipFromField;

        private Party ultimateCustomerField;

        private Party orderedByField;

        private Party senderField;

        private Party receiverField;

        /// <remarks/>
        public Party Buyer
        {
            get
            {
                return this.buyerField;
            }
            set
            {
                this.buyerField = value;
            }
        }

        /// <remarks/>
        public Party Invoicee
        {
            get
            {
                return this.invoiceeField;
            }
            set
            {
                this.invoiceeField = value;
            }
        }

        /// <remarks/>
        public Party Seller
        {
            get
            {
                return this.sellerField;
            }
            set
            {
                this.sellerField = value;
            }
        }

        /// <remarks/>
        public Party DeliveryPoint
        {
            get
            {
                return this.deliveryPointField;
            }
            set
            {
                this.deliveryPointField = value;
            }
        }

        /// <remarks/>
        public Party ShipFrom
        {
            get
            {
                return this.shipFromField;
            }
            set
            {
                this.shipFromField = value;
            }
        }

        /// <remarks/>
        public Party UltimateCustomer
        {
            get
            {
                return this.ultimateCustomerField;
            }
            set
            {
                this.ultimateCustomerField = value;
            }
        }

        /// <remarks/>
        public Party OrderedBy
        {
            get
            {
                return this.orderedByField;
            }
            set
            {
                this.orderedByField = value;
            }
        }

        /// <remarks/>
        public Party Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }

        /// <remarks/>
        public Party Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
    }
}